# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  pw-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: pw-mysql
    volumes:
      - pw-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=pw
      - MYSQL_USER=pw
      - MYSQL_PASSWORD=pw

  # PHP
  app:
    image: ambientum/php:7.2-nginx
    container_name: pw-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql